// Generated by CoffeeScript 1.4.0
(function() {
  var Derived, Super, x,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Super = (function() {

    function Super(mbr) {
      this.mbr = mbr;
    }

    Super.prototype.use = function() {
      return console.log(this.mbr);
    };

    return Super;

  })();

  Derived = (function(_super) {

    __extends(Derived, _super);

    function Derived(mbr) {
      this.mbr = mbr;
    }

    return Derived;

  })(Super);

  x = new Derived('hello');

  x.use();

}).call(this);
